import { FC } from 'react'
import styles from './Home.module.scss'
import { Navbar } from '../../components/Navbar/Navbar'
import Tools from '../../components/Tools/Tools'
import Filter from '../../components/Filter/Filter'
import CallsList from '../../components/CallsList/CallsList'
export const Home: FC = () => {
  return (
    <div>
      <Navbar />
      <div className={styles.home}>
        <div className={styles.conteiner}>
          <Tools />
          <Filter />
          <CallsList />
          <div>
            Hello and welcome! :) This app was generated by the Create React App
            template and bootstrapped with Redux, React Router, React Testing
            Library, TypeScript, ESlint, Prettier for you. Take a look around ;)
          </div>
        </div>
      </div>
      {/* <Counter /> */}
    </div>
  )
}
